apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      # TODO(calbach): Add health check probes.
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.dataExplorer.image.repository }}:{{ .Values.dataExplorer.image.tag }}"
          imagePullPolicy: {{ .Values.dataExplorer.image.pullPolicy }}
          args: [
            "-b", ":{{ .Values.dataExplorer.internalPort }}",
            "-e", "INDEX_ADDR={{ .Values.elastic.hostPort }}"
          ]
          ports:
            - containerPort: {{ .Values.dataExplorer.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: "{{ .Chart.Name }}-esp"
          image: "{{ .Values.esp.image.repository }}:{{ .Values.esp.image.tag }}"
          imagePullPolicy: {{ .Values.esp.image.pullPolicy }}
          args: [
            "-p", "{{ .Values.esp.internalPort }}",
            "-a", "127.0.0.1:{{ .Values.dataExplorer.internalPort }}",
            "-s", "{{ .Values.esp.serviceName }}",
            "-v", "{{ .Values.esp.serviceConfigId }}"
          ]
          ports:
            - containerPort: {{ .Values.esp.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
