# See https://github.com/clockworksoul/helm-elasticsearch/blob/master/values.yaml
service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "internal"

data:
  storage: 100Gi
